[package]
name = "drivetan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
filetime = "0.2.23"
pathdiff = "0.2.1"
walkdir = "2.5.0"
